name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch if different

permissions:
  contents: write  # Grant write access to repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-book-theme
          pip install .[dev]  # Install your development dependencies
          pip install coveralls

      - name: Build Sphinx documentation
        run: |
          sphinx-build -b html docs docs/_build/html  # Adjust paths as necessary

      - name: Run tests with coverage
        run: |
<<<<<<< HEAD
          coverage run --source=quends -m pytest tests/  # Run tests and generate coverage report
=======
          coverage run -source=quends -m pytest tests/  # Run tests and generate coverage report
>>>>>>> 75548bd (update deployment)
          coverage html  # Generate HTML coverage report

      - name: Prepare coverage report for deployment
        run: |
          mkdir -p docs/_build/html/coverage
          if [ -d htmlcov ]; then
            cp -r htmlcov/* docs/_build/html/coverage/
          else
            echo "htmlcov directory does not exist. Skipping coverage report copy."
          fi
          
      - name: Upload coverage to Coveralls
        run: coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html  # Publish Sphinx documentation
          publish_branch: gh-pages  # Specify the branch to publish to
          force_orphan: true

